
## Standard jekyll configuration

permalink: /articles/:title

#pygments: true

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

markdown: rdiscount

github:
  username: github/training.github.com

disqus:
  id: githubteachingmaterials

# Outputting

defaults:
  title: Avoin Lappi (Open Lapland)

## Site
